language: node_js
node_js: "node"

cache:
  directories:
  - website/node_modules

branches:
  only:
  - src

install:
  - wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb && sudo dpkg -i crowdin.deb

  - git config --global user.name "Travis CI"
  - git config --global user.email "contact@nfive.io"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc

  - cd website && npm install

script:
  - npm run write-translations
  - npm run crowdin-upload
  - npm run crowdin-download
  - GIT_USER="${GH_NAME}" npm run publish-gh-pages
